arbitrary java currency
KarazinScalaUsersGroup/circe-literal-extras pull request #13
Opened 2021-05-13 13:38 UTC by mikhailZakharevich

added an implicit that picks one element from java Currency

2021-05-13 15:54 UTC, VLADISLAV008 commented
Why is this Pull Request open into the `main` branch?

2021-05-13 15:57 UTC, mikhailZakharevich commented
Oops, overlooked this part

2021-05-13 16:23 UTC, IgorWolkov commented on src/test/scala/group/scala/karazin/circe/literal/extras/arbitraries/CurrencyArbitraries.scala
> +import io.circe.syntax._
Is there any unnecessary imports?

2021-05-13 16:24 UTC, IgorWolkov requested changes
Please cleanup imports if possible.

2021-05-13 18:55 UTC, mikhailZakharevich commented on src/test/scala/group/scala/karazin/circe/literal/extras/arbitraries/CurrencyArbitraries.scala
> +import io.circe.syntax._
Done

2021-05-14 14:21 UTC, IgorWolkov approved these changes

2021-05-14 14:32 UTC, merged