CLE-NST_AE - Add tests for Eithers
KarazinScalaUsersGroup/circe-literal-extras pull request #29
Opened 2021-05-20 12:42 UTC by IgorWolkov

2021-05-20 12:57 UTC, VLADISLAV008 commented on src/main/scala/group/scala/karazin/circe/literal/extras/macros.scala
> +          Json.fromFields(("Right", deconstructArgument[f]) :: Nil)
This implementation does not handle every possible case.
In the following case, there will be no compilation error:
```
        extension (inline sc: StringContext)
            inline def encode(inline args: Any*): Json =
               ${ macros.encode[Either[Int, List[String]]]('sc, 'args) }
              
        val value: Either[String, List[String]] = Left("")
           
          encode"""$value """
```

2021-05-20 13:01 UTC, VLADISLAV008 requested changes
I left a comment.

2021-05-20 13:51 UTC, IgorWolkov commented on src/main/scala/group/scala/karazin/circe/literal/extras/macros.scala
> +          Json.fromFields(("Right", deconstructArgument[f]) :: Nil)
Seems we have an issue in tests and this case must be added.

2021-05-21 17:41 UTC, VLADISLAV008 approved these changes
LGTM

2021-05-21 17:42 UTC, mikhailZakharevich approved these changes

2021-05-24 11:46 UTC, merged

2021-05-24 12:06 UTC, mikhailZakharevich commented on src/main/scala/group/scala/karazin/circe/literal/extras/macros.scala
>  end macros
needs an empty line at the eof

2021-05-24 12:26 UTC, mikhailZakharevich commented on src/main/scala/group/scala/karazin/circe/literal/extras/macros.scala
> +          ScalaTry(validateJsonSchema[T]("*", jsonSchema.hcursor)(using eitherLeftFreshKey, eitherRightFreshKey)) match {
Do you want to pass eitherLeftFreshKey, eitherRightFreshKey explicitly?